name: tzapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  freezed: ^3.0.4
  bloc: ^9.0.0
  equatable: ^2.0.7
  hive: ^2.2.3
  get_it: ^7.6.4
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.0
  auto_route: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  auto_route_generator: ^10.0.1
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
